std_msgs/Header header
sensor_msgs/Image back_img
sensor_msgs/Image decos_img
jsk_recognition_msgs/PlotData[] decos_rec_uv
geometry_msgs/Point[] decos_pos
geometry_msgs/Point[] decos_dims
geometry_msgs/Point bimg_lt_pos
geometry_msgs/Point bimg_rb_pos
geometry_msgs/Point[] planes_norm_vec
---
geometry_msgs/PoseArray result_pos
